### PR TITLE
Add support for finding all binaries with said name on path

### LINKED ISSUE #19: Variant to return all matching paths
`which` has the `-a` flag, which returns a list of _all_ of the executables that were found in PATH order instead of just the first one.

For some applications, it's useful to know if there were multiple options for a path being resolved.

In my case, I'm working on a toolchain manager and want to fall back to a system-wide installation of a tool under certain circumstances. In order to do that, I want to resolve my own executable name with `which`, but skip my own path.

### PR DESCRIPTION
**Pull request by Xaeroxe**
Closes #19, adding the ability to query all binaries with a particular name

### CODE REVIEW

**Comment by harryfei** [comment]
I will review it this weekend.

**Comment by Milo123459** [comment]
+1, when is this going to be merged @harryfei?

**Comment by harryfei** [comment]
Sorry, I've been quite busy the last few months. I added @Xaeroxe and @Milo123459 as collaborators. You guys can merge anything you want.

**Comment by Milo123459** [comment]
Thanks, I'm going to merge this.

**Pull request merged**
