### PR TITLE
Fix clippy

### PR DESCRIPTION
**Pull request by ever0de**

### CODE REVIEW

**Comment by ever0de** [comment]
The current error is something strange
The type of `mode_t` in libc is `u16`.

**Comment by harryfei** [comment]
@ever0de just use [Conditional compilation](https://doc.rust-lang.org/reference/conditional-compilation.html#conditional-compilation). 

eg. [#cfg(target_os="macos")]

**Comment by ever0de** [comment]
<https://github.com/harryfei/which-rs/actions/runs/3985401962/jobs/6832743628>

I found it once more and did a force-push 😓

**Comment by harryfei** [comment]
@ever0de Thank you!.

**Pull request merged**
