### PR TITLE
Removed unnecessary depedendency on std

### PR DESCRIPTION
**Pull request by WorksButNotTested**

### CODE REVIEW

**Comment by Xaeroxe** [comment]
This is a really interesting use case, in what context do you need to scan a filesystem and don't have access to `std`?

**Comment by Xaeroxe** [comment]
Side note, `which` uses the `fs` module in `std` which doesn't exist in `core`, so this library doesn't achieve the stated goal.

**Comment by WorksButNotTested** [comment]
Hi. Thanks for the quick response. My PR is a work around for this issue with rust itself. https://github.com/rust-lang/rust/issues/107845

One of my dependencies has bindgen as a build dependency and results in std being pulled into my target binary!

**Comment by WorksButNotTested** [comment]
This change appears to leave bindgen working just fine, so seems to work in my use case. But as you say, may not suit the general case as I first thought.

**Comment by Xaeroxe** [comment]
Yeah this is fixing the problem by accident then. [I left a comment on your issue, let's continue talking there.](https://github.com/rust-lang/rust/issues/107845#issuecomment-1424934369)

**Pull request closed without merging**
