### PR TITLE
Move tests into separate file

### PR DESCRIPTION
**Pull request by spl**
It seemed like the `test` module in `src/lib.rs` was quite large and worthy of moving into a separate file. I'd like to contribute something else, and this change clears up some “clutter” in `src/lib.rs`.

I was getting deprecated warnings for `AsciiExt`, so I added `#[allow(deprecated)]` to it.

I'm not sure what minimum version of Rust you want to support, but would it be easy to test that version to make sure I didn't break anything?

### CODE REVIEW

**Comment by harryfei** [comment]
Oh Thanks.
I think we can remove the `AsciiExt` compatibility now. We shouldn't support this deprecated API any more.
Besides, the code fails to build on `windows-gnu` target. Could you check it?

**Comment by spl** [comment]
Done.

**Comment by harryfei** [comment]
I will publish a new version (v3.0.0) on crates.io. Removing the `AsciiExt` compatibility is a breaking change.
Thanks for your work. :tada:

**Comment by spl** [comment]
Before you do that, would you consider another change?

**Comment by harryfei** [comment]
Yeah, Sure. @spl

**Comment by spl** [comment]
See #13.

**Pull request merged**
